name: take_medication
description: "A privacy-first, offline-capable medication companion that never lets a dose slip."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core dependencies
  cupertino_icons: ^1.0.8
  
  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # Database & local storage
  supabase_flutter: ^2.3.4
  # drift: ^2.18.0  # Commented out - replacing with Supabase
  # path_provider: ^2.1.2  # Commented out - replacing with Supabase
  # path: ^1.8.3  # Commented out - replacing with Supabase
  
  # Navigation
  go_router: ^14.2.0
  
  # Theming
  flex_color_scheme: ^7.3.1
  
  # Notifications & scheduling
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.11
  drift_dev: ^2.18.0
  riverpod_generator: ^2.4.3
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1

flutter:
  uses-material-design: true
  
  # Assets
  # assets:
  #   - images/
  
  # Fonts
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
