name: smartstudy
description: "A comprehensive educational platform for students and teachers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Design
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.0.0

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Supabase packages
  supabase_flutter: ^2.3.4

  # Navigation and Routing
  go_router: ^13.2.0

  # Utilities
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1

  # Charts and Analytics
  fl_chart: ^0.66.2

  # Video and Media
  video_player: ^2.8.2
  chewie: ^1.7.4

  # PDF and Documents
  syncfusion_flutter_pdfviewer: ^24.2.9

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/data/
